export const cheatsheets: Record<number, { title: string; items: { code: string; desc: string }[] }> = {
  0: {
    title: "Ввод/Вывод",
    items: [
      { code: 'print("текст")', desc: "Вывести текст на экран" },
      { code: "name = input()", desc: "Прочитать ввод пользователя" },
      { code: 'print(f"Привет, {name}!")', desc: "f-строка — вставка переменной в текст" },
      { code: "print(a, b)", desc: "Вывести несколько значений через пробел" },
      { code: 'print(a, b, sep=", ")', desc: "Вывести с кастомным разделителем" },
      { code: "# комментарий", desc: "Комментарий — Python его игнорирует" },
    ],
  },
  1: {
    title: "Переменные и типы",
    items: [
      { code: "x = 10", desc: "Создать переменную с числом" },
      { code: 'name = "Аня"', desc: "Создать переменную со строкой" },
      { code: "type(x)", desc: "Узнать тип переменной" },
      { code: "int(s)", desc: "Преобразовать строку в целое число" },
      { code: "float(s)", desc: "Преобразовать строку в дробное число" },
      { code: "str(n)", desc: "Преобразовать число в строку" },
      { code: "a, b = 1, 2", desc: "Присвоить несколько переменных сразу" },
    ],
  },
  2: {
    title: "Условия",
    items: [
      { code: "if x > 0:", desc: "Если условие истинно — выполни блок" },
      { code: "elif x == 0:", desc: "Иначе если — дополнительная проверка" },
      { code: "else:", desc: "Иначе — если ничего выше не сработало" },
      { code: "==, !=, <, >, <=, >=", desc: "Операторы сравнения" },
      { code: "and, or, not", desc: "Логические операторы" },
      { code: "x % 2 == 0", desc: "Проверка на чётность" },
      { code: 'if "a" in s:', desc: "Проверка вхождения подстроки" },
    ],
  },
  3: {
    title: "Циклы и списки",
    items: [
      { code: "while x > 0:", desc: "Цикл пока условие истинно" },
      { code: "for i in range(n):", desc: "Цикл от 0 до n-1" },
      { code: "for item in lst:", desc: "Перебор элементов списка" },
      { code: "break", desc: "Выйти из цикла досрочно" },
      { code: "continue", desc: "Перейти к следующей итерации" },
      { code: "lst = [1, 2, 3]", desc: "Создать список" },
      { code: "lst.append(x)", desc: "Добавить элемент в конец списка" },
      { code: "len(lst)", desc: "Длина списка" },
    ],
  },
  4: {
    title: "Функции",
    items: [
      { code: "def greet(name):", desc: "Объявить функцию с параметром" },
      { code: "return result", desc: "Вернуть значение из функции" },
      { code: "greet(\"Аня\")", desc: "Вызвать функцию с аргументом" },
      { code: "def f(a, b=10):", desc: "Параметр со значением по умолчанию" },
      { code: "def f(a: int) -> str:", desc: "Подсказки типов (аннотации)" },
      { code: "lambda x: x * 2", desc: "Анонимная (лямбда) функция" },
    ],
  },
  5: {
    title: "Строки подробнее",
    items: [
      { code: "s[0], s[-1]", desc: "Первый и последний символ" },
      { code: "s[1:4]", desc: "Срез — символы с 1 по 3" },
      { code: "s[::-1]", desc: "Строка задом наперёд" },
      { code: "s.upper(), s.lower()", desc: "Верхний / нижний регистр" },
      { code: "s.split()", desc: "Разбить строку на список слов" },
      { code: '" ".join(lst)', desc: "Собрать список в строку через пробел" },
      { code: "s.replace(a, b)", desc: "Заменить подстроку a на b" },
      { code: "s.strip()", desc: "Убрать пробелы по краям" },
    ],
  },
  6: {
    title: "Словари",
    items: [
      { code: 'd = {"a": 1, "b": 2}', desc: "Создать словарь" },
      { code: 'd["a"]', desc: "Получить значение по ключу" },
      { code: 'd["c"] = 3', desc: "Добавить / изменить значение" },
      { code: "d.get(key, default)", desc: "Получить значение или default" },
      { code: "for k, v in d.items():", desc: "Перебрать пары ключ-значение" },
      { code: "d.keys(), d.values()", desc: "Все ключи / все значения" },
      { code: '"a" in d', desc: "Проверить наличие ключа" },
    ],
  },
  7: {
    title: "Продвинутые функции",
    items: [
      { code: "def f(*args):", desc: "Принять любое количество аргументов" },
      { code: "def f(**kwargs):", desc: "Принять именованные аргументы" },
      { code: "sorted(lst, key=func)", desc: "Сортировка с ключом" },
      { code: "map(func, lst)", desc: "Применить функцию к каждому элементу" },
      { code: "filter(func, lst)", desc: "Отфильтровать элементы" },
      { code: "def outer():\n  def inner():", desc: "Вложенная функция" },
    ],
  },
  8: {
    title: "Мини-проекты",
    items: [
      { code: "count += 1", desc: "Увеличить счётчик на 1" },
      { code: 'words = s.split(" ")', desc: "Разбить строку на слова" },
      { code: "lst[::-1]", desc: "Перевернуть список" },
      { code: "len(s) >= 8", desc: "Проверить длину строки" },
      { code: "any(c.isdigit() for c in s)", desc: "Есть ли цифра в строке" },
      { code: "all(x > 0 for x in lst)", desc: "Все ли элементы положительны" },
    ],
  },
  9: {
    title: "Вложенные циклы",
    items: [
      { code: "for i in range(n):\n  for j in range(m):", desc: "Двойной вложенный цикл" },
      { code: 'print("*" * n)', desc: "Строка из n звёздочек" },
      { code: 'print(end="")', desc: "print без перевода строки" },
      { code: "range(1, n+1)", desc: "Диапазон от 1 до n включительно" },
      { code: "for i in range(n, 0, -1):", desc: "Цикл в обратном порядке" },
      { code: 'f"{i*j:4d}"', desc: "Форматирование ширины числа" },
    ],
  },
  10: {
    title: "Кортежи и множества",
    items: [
      { code: "t = (1, 2, 3)", desc: "Создать кортеж (нельзя менять)" },
      { code: "a, b, c = t", desc: "Распаковка кортежа" },
      { code: "s = {1, 2, 3}", desc: "Создать множество (уникальные)" },
      { code: "s.add(x)", desc: "Добавить элемент в множество" },
      { code: "s1 & s2", desc: "Пересечение множеств" },
      { code: "s1 | s2", desc: "Объединение множеств" },
      { code: "s1 - s2", desc: "Разность множеств" },
      { code: "set(lst)", desc: "Убрать дубликаты из списка" },
    ],
  },
  11: {
    title: "Генераторы списков",
    items: [
      { code: "[x**2 for x in range(10)]", desc: "Список квадратов от 0 до 9" },
      { code: "[x for x in lst if x > 0]", desc: "Отфильтровать положительные" },
      { code: "[s.upper() for s in words]", desc: "Привести все слова к верхнему регистру" },
      { code: "[int(x) for x in parts]", desc: "Преобразовать все элементы в числа" },
      { code: "{k: v for k, v in items}", desc: "Генератор словаря" },
      { code: "{x for x in lst}", desc: "Генератор множества" },
    ],
  },
  12: {
    title: "Работа с текстом",
    items: [
      { code: "s.count(sub)", desc: "Сколько раз встречается подстрока" },
      { code: "s.find(sub)", desc: "Индекс первого вхождения (-1 если нет)" },
      { code: "s.startswith(p)", desc: "Начинается ли строка с p" },
      { code: "s.endswith(p)", desc: "Заканчивается ли строка на p" },
      { code: "s.isdigit()", desc: "Состоит ли строка только из цифр" },
      { code: "s.isalpha()", desc: "Состоит ли строка только из букв" },
      { code: 'f"{x:>10}"', desc: "Выровнять вправо на 10 символов" },
    ],
  },
  13: {
    title: "Обработка ошибок",
    items: [
      { code: "try:\n  ...\nexcept:", desc: "Обработать любую ошибку" },
      { code: "except ValueError:", desc: "Поймать конкретный тип ошибки" },
      { code: "except (TypeError, ValueError):", desc: "Поймать несколько типов" },
      { code: "except Exception as e:", desc: "Сохранить ошибку в переменную" },
      { code: "finally:", desc: "Выполнить в любом случае" },
      { code: 'raise ValueError("msg")', desc: "Вызвать ошибку вручную" },
    ],
  },
  14: {
    title: "Мини-проекты 2",
    items: [
      { code: "random.choice(lst)", desc: "Случайный элемент из списка" },
      { code: "random.randint(a, b)", desc: "Случайное число от a до b" },
      { code: "sum(lst) / len(lst)", desc: "Среднее арифметическое" },
      { code: "max(lst), min(lst)", desc: "Максимум и минимум списка" },
      { code: "sorted(d.items(), key=lambda x: x[1])", desc: "Сортировка словаря по значению" },
      { code: "chr(ord(c) + n)", desc: "Сдвиг символа на n позиций (шифр)" },
    ],
  },
  15: {
    title: "Классы: основы",
    items: [
      { code: "class Dog:", desc: "Объявить класс" },
      { code: "def __init__(self, name):", desc: "Конструктор — вызывается при создании" },
      { code: "self.name = name", desc: "Атрибут экземпляра" },
      { code: "d = Dog(\"Рекс\")", desc: "Создать экземпляр класса" },
      { code: "def bark(self):", desc: "Метод класса" },
      { code: "def __str__(self):", desc: "Строковое представление объекта" },
    ],
  },
  16: {
    title: "Наследование",
    items: [
      { code: "class Cat(Animal):", desc: "Cat наследует от Animal" },
      { code: "super().__init__(name)", desc: "Вызвать конструктор родителя" },
      { code: "isinstance(obj, Cat)", desc: "Проверить тип объекта" },
      { code: "def speak(self):", desc: "Переопределить метод родителя" },
      { code: "class A(B, C):", desc: "Множественное наследование" },
      { code: "issubclass(Cat, Animal)", desc: "Проверить наследование классов" },
    ],
  },
  17: {
    title: "Инкапсуляция",
    items: [
      { code: "self._balance = 0", desc: "Защищённый атрибут (соглашение)" },
      { code: "self.__secret = 42", desc: "Приватный атрибут (name mangling)" },
      { code: "@property", desc: "Геттер — доступ как к атрибуту" },
      { code: "@name.setter", desc: "Сеттер — контроль при записи" },
      { code: "def get_balance(self):", desc: "Геттер-метод (альтернатива)" },
      { code: "def set_balance(self, v):", desc: "Сеттер-метод (альтернатива)" },
    ],
  },
  18: {
    title: "Статические и классовые методы",
    items: [
      { code: "@staticmethod", desc: "Метод без доступа к self/cls" },
      { code: "@classmethod", desc: "Метод с доступом к классу (cls)" },
      { code: "cls.count += 1", desc: "Изменить атрибут класса" },
      { code: "MyClass.class_var", desc: "Обращение к атрибуту класса" },
      { code: "def from_string(cls, s):", desc: "Фабричный метод (@classmethod)" },
      { code: "def validate(value):", desc: "Утилита без self (@staticmethod)" },
    ],
  },
  19: {
    title: "ООП на практике",
    items: [
      { code: "class Inventory:", desc: "Класс-контейнер с логикой" },
      { code: "def __len__(self):", desc: "Поддержка len(obj)" },
      { code: "def __getitem__(self, i):", desc: "Поддержка obj[i]" },
      { code: "def __contains__(self, x):", desc: "Поддержка x in obj" },
      { code: "def __repr__(self):", desc: "Представление для отладки" },
      { code: "def __eq__(self, other):", desc: "Сравнение объектов через ==" },
    ],
  },
};
