export interface FormulaSection {
  title: string;
  icon: string;
  formulas: { name: string; formula: string; note?: string }[];
}

export const formulaSections: FormulaSection[] = [
  {
    title: "Геометрия (плоскость)",
    icon: "📐",
    formulas: [
      { name: "Площадь треугольника", formula: "S = ½ · a · h", note: "a — основание, h — высота" },
      { name: "Площадь треугольника (по сторонам)", formula: "S = √(p(p−a)(p−b)(p−c))", note: "Формула Герона, p = (a+b+c)/2" },
      { name: "Площадь треугольника (через синус)", formula: "S = ½ · a · b · sin(C)", note: "C — угол между сторонами a и b" },
      { name: "Площадь прямоугольника", formula: "S = a · b" },
      { name: "Площадь параллелограмма", formula: "S = a · h", note: "a — сторона, h — высота к ней" },
      { name: "Площадь трапеции", formula: "S = ½ · (a + b) · h", note: "a, b — основания, h — высота" },
      { name: "Площадь ромба", formula: "S = ½ · d₁ · d₂", note: "d₁, d₂ — диагонали" },
      { name: "Площадь круга", formula: "S = π · r²" },
      { name: "Длина окружности", formula: "L = 2π · r" },
      { name: "Периметр прямоугольника", formula: "P = 2(a + b)" },
      { name: "Теорема Пифагора", formula: "c² = a² + b²", note: "c — гипотенуза" },
      { name: "Теорема синусов", formula: "a/sin(A) = b/sin(B) = c/sin(C) = 2R" },
      { name: "Теорема косинусов", formula: "c² = a² + b² − 2ab · cos(C)" },
    ],
  },
  {
    title: "Геометрия (пространство)",
    icon: "📦",
    formulas: [
      { name: "Объём куба", formula: "V = a³" },
      { name: "Площадь поверхности куба", formula: "S = 6a²" },
      { name: "Объём параллелепипеда", formula: "V = a · b · c" },
      { name: "Площадь поверхности параллелепипеда", formula: "S = 2(ab + bc + ac)" },
      { name: "Объём цилиндра", formula: "V = π · r² · h" },
      { name: "Площадь боковой поверхности цилиндра", formula: "S = 2π · r · h" },
      { name: "Полная поверхность цилиндра", formula: "S = 2π · r · (r + h)" },
      { name: "Объём конуса", formula: "V = ⅓ · π · r² · h" },
      { name: "Площадь боковой поверхности конуса", formula: "S = π · r · l", note: "l — образующая" },
      { name: "Объём шара", formula: "V = ⁴⁄₃ · π · r³" },
      { name: "Площадь поверхности шара", formula: "S = 4π · r²" },
      { name: "Объём пирамиды", formula: "V = ⅓ · S_осн · h", note: "S_осн — площадь основания" },
    ],
  },
  {
    title: "Алгебра",
    icon: "🔢",
    formulas: [
      { name: "Квадрат суммы", formula: "(a + b)² = a² + 2ab + b²" },
      { name: "Квадрат разности", formula: "(a − b)² = a² − 2ab + b²" },
      { name: "Разность квадратов", formula: "a² − b² = (a − b)(a + b)" },
      { name: "Куб суммы", formula: "(a + b)³ = a³ + 3a²b + 3ab² + b³" },
      { name: "Куб разности", formula: "(a − b)³ = a³ − 3a²b + 3ab² − b³" },
      { name: "Сумма кубов", formula: "a³ + b³ = (a + b)(a² − ab + b²)" },
      { name: "Разность кубов", formula: "a³ − b³ = (a − b)(a² + ab + b²)" },
      { name: "Дискриминант", formula: "D = b² − 4ac" },
      { name: "Корни квадратного уравнения", formula: "x = (−b ± √D) / (2a)" },
      { name: "Теорема Виета", formula: "x₁ + x₂ = −b/a,  x₁ · x₂ = c/a", note: "Для ax² + bx + c = 0" },
      { name: "Свойства степеней", formula: "aⁿ · aᵐ = aⁿ⁺ᵐ,  aⁿ / aᵐ = aⁿ⁻ᵐ,  (aⁿ)ᵐ = aⁿ·ᵐ" },
      { name: "Корень из степени", formula: "ⁿ√(aᵐ) = aᵐ/ⁿ" },
    ],
  },
  {
    title: "Логарифмы",
    icon: "📊",
    formulas: [
      { name: "Определение", formula: "log_a(b) = c  ⟺  aᶜ = b", note: "a > 0, a ≠ 1, b > 0" },
      { name: "Логарифм произведения", formula: "log_a(x · y) = log_a(x) + log_a(y)" },
      { name: "Логарифм частного", formula: "log_a(x / y) = log_a(x) − log_a(y)" },
      { name: "Логарифм степени", formula: "log_a(xⁿ) = n · log_a(x)" },
      { name: "Переход к другому основанию", formula: "log_a(b) = log_c(b) / log_c(a)" },
      { name: "Логарифм единицы", formula: "log_a(1) = 0" },
      { name: "Логарифм основания", formula: "log_a(a) = 1" },
      { name: "Основное свойство", formula: "a^(log_a(b)) = b" },
    ],
  },
  {
    title: "Тригонометрия",
    icon: "📉",
    formulas: [
      { name: "sin 0° = 0", formula: "sin 30° = ½,  sin 45° = √2/2,  sin 60° = √3/2,  sin 90° = 1" },
      { name: "cos 0° = 1", formula: "cos 30° = √3/2,  cos 45° = √2/2,  cos 60° = ½,  cos 90° = 0" },
      { name: "tg 0° = 0", formula: "tg 30° = √3/3,  tg 45° = 1,  tg 60° = √3", note: "tg 90° не определён" },
      { name: "Основное тождество", formula: "sin²(x) + cos²(x) = 1" },
      { name: "Тангенс", formula: "tg(x) = sin(x) / cos(x)" },
      { name: "Связь tg и cos", formula: "1 + tg²(x) = 1 / cos²(x)" },
      { name: "Синус двойного угла", formula: "sin(2x) = 2 · sin(x) · cos(x)" },
      { name: "Косинус двойного угла", formula: "cos(2x) = cos²(x) − sin²(x) = 2cos²(x) − 1 = 1 − 2sin²(x)" },
      { name: "Формулы приведения (π/2)", formula: "sin(π/2 − x) = cos(x),  cos(π/2 − x) = sin(x)" },
    ],
  },
  {
    title: "Производные",
    icon: "📈",
    formulas: [
      { name: "Производная константы", formula: "(C)' = 0" },
      { name: "Производная x", formula: "(x)' = 1" },
      { name: "Степенная функция", formula: "(xⁿ)' = n · xⁿ⁻¹" },
      { name: "Корень", formula: "(√x)' = 1 / (2√x)" },
      { name: "Синус", formula: "(sin x)' = cos x" },
      { name: "Косинус", formula: "(cos x)' = −sin x" },
      { name: "Тангенс", formula: "(tg x)' = 1 / cos²(x)" },
      { name: "Экспонента", formula: "(eˣ)' = eˣ" },
      { name: "Показательная", formula: "(aˣ)' = aˣ · ln(a)" },
      { name: "Натуральный логарифм", formula: "(ln x)' = 1/x" },
      { name: "Логарифм", formula: "(log_a(x))' = 1 / (x · ln(a))" },
      { name: "Правило суммы", formula: "(f ± g)' = f' ± g'" },
      { name: "Правило произведения", formula: "(f · g)' = f' · g + f · g'" },
      { name: "Правило частного", formula: "(f / g)' = (f' · g − f · g') / g²" },
      { name: "Сложная функция", formula: "(f(g(x)))' = f'(g(x)) · g'(x)" },
    ],
  },
  {
    title: "Вероятность",
    icon: "🎲",
    formulas: [
      { name: "Классическая вероятность", formula: "P(A) = m / n", note: "m — благоприятные, n — все исходы" },
      { name: "Сложение (несовместные)", formula: "P(A ∪ B) = P(A) + P(B)" },
      { name: "Сложение (общий случай)", formula: "P(A ∪ B) = P(A) + P(B) − P(A ∩ B)" },
      { name: "Умножение (независимые)", formula: "P(A ∩ B) = P(A) · P(B)" },
      { name: "Противоположное событие", formula: "P(Ā) = 1 − P(A)" },
      { name: "Формула Бернулли", formula: "P(k) = C(n,k) · pᵏ · (1−p)ⁿ⁻ᵏ", note: "k успехов из n испытаний" },
      { name: "Число сочетаний", formula: "C(n,k) = n! / (k! · (n−k)!)" },
    ],
  },
];
